document.write("<center><h1>variable let or const</h1></center>")
document.write("<center>2nd variable let</center>")
let a = ("Danish chouhan")
document.write(a)
document.write("<hr>")
document.write("<center>3rd variable const</center>")
const b = ("Danish chouhan")
document.write(b)